# Payments app — prod infrastructure.
# Generated by the Acme IaC self-service platform from Azure Verified Modules.
# Compliant with Acme standards (naming, tags, regions, security baseline).
#
# Verify before apply:  terraform init && terraform plan

data "azurerm_client_config" "current" {}

locals {
  common_tags = {
    environment = "prod"
    owner       = "net9876@gmail.com"
    cost_center = "CC-PAYMENTS-001"
    project     = "payments"
    managed_by  = "terraform"
  }
}

# Generated admin password — fed to Postgres as a write-only arg (never in state)
# and stored in Key Vault for application retrieval (SEC-SECRET-001).
resource "random_password" "pg_admin" {
  length           = 24
  special          = true
  override_special = "!#$%*()-_=+[]{}"
}

# --- Foundation -------------------------------------------------------------
module "resource_group" {
  source  = "Azure/avm-res-resources-resourcegroup/azurerm"
  version = "0.4.0"

  name     = "acme-prod-payments-rg01"
  location = "westeurope"
  tags     = local.common_tags
}

# --- Networking (parent_id wiring) ------------------------------------------
module "virtual_network" {
  source  = "Azure/avm-res-network-virtualnetwork/azurerm"
  version = "0.17.1"

  name          = "acme-prod-payments-vnet01"
  location      = "westeurope"
  parent_id     = module.resource_group.resource_id
  address_space = ["10.20.0.0/16"]
  subnets = {
    private-endpoints = { name = "private-endpoints", address_prefixes = ["10.20.0.0/24"] }
    db                = { name = "db", address_prefixes = ["10.20.1.0/24"] }
    app               = { name = "app", address_prefixes = ["10.20.2.0/24"] }
  }
  tags = local.common_tags
}

# --- Key Vault (resource_group_name wiring; native secret management) -------
module "key_vault" {
  source  = "Azure/avm-res-keyvault-vault/azurerm"
  version = "0.10.2"

  name                = "acme-prod-payments-kv01"
  location            = "westeurope"
  resource_group_name = module.resource_group.name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  secrets = {
    pg-admin = { name = "pg-admin" }
  }
  secrets_value = {
    pg-admin = random_password.pg_admin.result
  }
  tags = local.common_tags
}

# --- Storage (parent_id wiring; Entra-only auth) ----------------------------
module "storage_account" {
  source  = "Azure/avm-res-storage-storageaccount/azurerm"
  version = "0.7.2"

  name                      = "acmeprodpaymentsst01"
  location                  = "westeurope"
  parent_id                 = module.resource_group.resource_id
  account_replication_type  = "ZRS"
  shared_access_key_enabled = false # SEC-STORAGE-002
  tags                      = local.common_tags
}

# --- PostgreSQL (resource_group_name wiring; write-only password) -----------
module "postgresql_flexible" {
  source  = "Azure/avm-res-dbforpostgresql-flexibleserver/azurerm"
  version = "0.2.2"

  name                = "acme-prod-payments-psql01"
  location            = "westeurope"
  resource_group_name = module.resource_group.name

  administrator_login               = "pgadmin"
  administrator_password_wo         = random_password.pg_admin.result # write-only: not in state
  administrator_password_wo_version = 1

  tags = local.common_tags
}
